Ogc 241 map
OneGov/onegov-cloud pull request #494
Opened 2022-08-31 09:45 UTC by BreathingFlesh

2022-08-31 12:22 UTC, msom requested changes

2022-08-31 12:22 UTC, msom commented on src/onegov/core/translate_coordinates.py
> +# -*- coding: utf-8 -*-
No need for encoding

2022-08-31 12:22 UTC, msom commented on src/onegov/org/app.py
> +    policy.child_src.add('https://map.geo.admin.ch')
Do wee need this?

2022-08-31 12:22 UTC, msom commented on tests/onegov/agency/test_forms.py
>      ]
Please also test actual data like the other fields

2022-09-01 07:36 UTC, BreathingFlesh commented on src/onegov/org/app.py
> +    policy.connect_src.add('https://wmts.geo.bs.ch')
Just checked, we do.

2022-09-01 07:42 UTC, BreathingFlesh commented on src/onegov/org/app.py
> +    policy.child_src.add('https://map.geo.admin.ch')
We don't.

2022-09-02 08:24 UTC, merged