Election Day: Show timestamp of when the last archive was generated.
OneGov/onegov-cloud pull request #671
Opened 2023-01-26 17:00 UTC by cyrillkuettel

## Commit message

Election Day: Show timestamp of when the last archive was generated.

TYPE: Feature
LINK: OGC-885

## Checklist

- [X] I considered adding a reviewer
- [X] I have tested my code thoroughly by hand
- [X] I have updated the PO files

2023-01-30 06:45 UTC, msom commented
Please do not merge before 13.2

2023-01-30 13:46 UTC, BreathingFlesh requested changes

2023-01-30 13:46 UTC, BreathingFlesh commented on src/onegov/election_day/templates/archive.pt
> +                        <p tal:condition="timestamp"><a i18n:translate href="${layout.archive_download}">Download the entire archive (Status: <tal:block tal:content="layout.format_date(timestamp, 'da
This way the option of downloading the archive does not appear when the archive has never been downloaded before. I wold put the Status in a `<tal:b>` and set the condition there.

2023-03-06 07:59 UTC, msom requested changes

2023-03-06 07:59 UTC, msom commented on src/onegov/election_day/templates/archive.pt
> +                    <div tal:define="timestamp layout.last_archive_modification" >
use tal:block instead of div

2023-03-22 14:06 UTC, merged